package com.komsije.booking.model;

public enum Settings {
    RESERVATION_REQUEST_NOTIFICATION, RESERVATION_CANCEL_NOTIFICATION, HOST_REVIEW_NOTIFICATION, ACCOMMODATION_REVIEW_NOTIFICATION, RESERVATION_RESPONSE_NOTIFICATION
}
